### ISSUE TITLE
Unable to add...

### ISSUE THREAD

**Issue by Mario6425** [reiryuki/Audio-Modification-Library#1]
Hey :)
 I use an OP 11 cph2449 with Oos14.
I always get the following error in the (use the latest kitsune mask version) log after flashing. 
- Unable to add: /vendor/odm,
skipped 
-Unable to add: /system/my_product, skipped
-Unable to add: /system/odm, skipped.

Even if I rewrite my partitions to ext4 + r/w I get this error message. Only linking the folders makes the errors disappear. But I am not sure if this is the right way.

The installation log looks good

![Screenshot_2024-02-04-15-24-12-34_e49d45507bc181c986c3a6e97c85ef40](https://github.com/reiryuki/Audio-Modification-Library-Ryuki-Mod-Magisk-Module/assets/115133131/a0ae2155-e1b7-4091-aabc-773a6d72b9a5)

**Comment by reiryuki** [comment]
That's not an issue
Just ignore that
